### ISSUE TITLE
LibreNMS version checkout

### ISSUE THREAD

**Issue by RalfHerzog** [setiseta/docker-librenms#12]
For stability reasons the LibreNMS source should be checked out based on a specific [release](https://github.com/librenms/librenms/releases).

What about an environment variable called `LIBRENMS_VERSION` with the value of a `git checkout [VERSION]` from [LibreNMS Tags](https://github.com/librenms/librenms/tags)? The default can be the `master` branch.
After the `git clone` command [here](https://github.com/setiseta/docker-librenms/blob/2d0e5d4f61072f1eb605283f08697bce258bb132/init.sh#L19) in `init.sh` should be a `git checkout` to the specified version

**Comment by setiseta** [comment]
This is a good idea.
How is it with the release and the daily update? I think this needs to be disabled then?
Or is there a check for a 'release update' mode?
Or do we need then a LIBRENMS_VERSION and if this is set, disable the update automatical.
Or add an additional flag to enable or disable the update.

**Comment by RalfHerzog** [comment]
Ah, i see. The LibreNMS source updates [itself](https://docs.librenms.org/#General/Updating/).
I just looked at the update process. There seems to be a config variable 'update_channel' (undocumented too) defining the update branch `master` or `release` (see [here](https://github.com/librenms/librenms/blob/0def643e09ea88e72ef71266fa09a185067a82a3/daily.php#L25)). Either the exit code is 1 (=master) or (3=release) the daily.sh updates to the [master](https://github.com/librenms/librenms/blob/de8bcf3a6c0894d5026ecc23a7bd91006b153add/daily.sh#L165) branch or the [latest tag](https://github.com/librenms/librenms/blob/de8bcf3a6c0894d5026ecc23a7bd91006b153add/daily.sh#L171).
So, to stay with a specific tag/release seems not to be the philosophy of the LibreNMS developers. Should we define an variable for 'update_channel' eg. `UPDATE_CHANNEL=release`?

**Comment by setiseta** [comment]
Yes this seems a good idea.
I've tested it and done the commit: c6c9f56
Docker images is available.

It would be nice if you can test an close the issue if its ok for you.

**Comment by setiseta** [comment]
Yes this seems a good idea.
I've tested it and done the commit: c6c9f56
Docker images is available.

It would be nice if you can test an close the issue if its ok for you.

**Comment by RalfHerzog** [comment]
Looks good so far. Could you please add some documentation to the docker-compose.yml and README.md for `UPDATE_CHANNEL`?

**Comment by setiseta** [comment]
It is documented in README.md in section 'Environment Vars'.
I have added it to the docker-compose with the commit:  1ff49b7

**Comment by RalfHerzog** [comment]
Alright, thanks :-)
