### ISSUE TITLE
Switch update_channel and setup

### ISSUE THREAD

**Issue by RalfHerzog** [setiseta/docker-librenms#14]
I noticed that the commit c6c9f56c52441c0c53ad47d1963d3c16798d5273 updates the LibreNMS source even if it is not previously setup. The container does not start up after several minutes.
The setup should be done before the update, so please switch the order

**Comment by setiseta** [comment]
I have tested it with an empty database, let me recheck this.
This was done because of the Database schema not setup to the master if you are on Release channel, so its needed to update the source previously.

**Comment by RalfHerzog** [comment]
My setup got stuck at this point:
```
librenms-db | 2017-10-20 12:41:28 140443316631296 [Note] InnoDB: Buffer pool(s) load completed at 171020 12:41:28
librenms-db | 2017-10-20 12:41:28 140444221511552 [Note] Plugin 'FEEDBACK' is disabled.
librenms-db | 2017-10-20 12:41:28 140444221511552 [Note] Server socket created on IP: '::'.
librenms-db | 2017-10-20 12:41:28 140444221511552 [Warning] 'proxies_priv' entry '@% root@3ff6683782e7' ignored in --skip-name-resolve mode.
librenms-db | 2017-10-20 12:41:28 140444221511552 [Note] Reading of all Master_info entries succeded
librenms-db | 2017-10-20 12:41:28 140444221511552 [Note] Added new Master_info '' to hash table
librenms-db | 2017-10-20 12:41:28 140444221511552 [Note] mysqld: ready for connections.
librenms-db | Version: '10.2.9-MariaDB-10.2.9+maria~jessie'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
librenms    | ..........DB onnection is ok
librenms    | mysql: [Warning] Using a password on the command line interface can be insecure.
librenms    | ============================================
librenms    | run daily to switch to update channel
librenms    | Re-running /opt/librenms/daily.sh as librenms user
librenms    | Updating to latest codebase                        OK
=> Nothing seems to change afterwards
```
I got really high IO disk usage. Maybe that helps

**Comment by setiseta** [comment]
At this point it needs some time. There it setup the database schema.
I've retestet, with master and release channel.
Both are coming up.
whats your database?

**Comment by RalfHerzog** [comment]
Thats the point! Previously the setup shows the setup progress for the database. I was just a bit to impatient.
So the database setup is done at the daily.sh script. Not nice, but okay. Do we need the snippet to setup the database at the first start? I think that can be removed.
```
cd /opt/librenms
if [ -z "${COUNT}" -o ${COUNT} -eq 0 ]; then
	echo "Setting up Librenms for firstrun."
	php build-base.php
	php adduser.php librenms librenms 10
	#php addhost.php localhost public v2c
fi
```

**Comment by RalfHerzog** [comment]
Okay it cannot be removed. The {COUNT} variable holds the information if the database was setup prior the daily.sh update. Can we get any problems running daily.sh before
```
php build-base.php
php adduser.php librenms librenms 10
```
?

**Comment by setiseta** [comment]
It needs to setup the database by the daily.sh cause if the master is ahead there is a different database schema.
The snippet with COUNT is needet to insert default user if there is none.

I havent checked the code if it could get a problem, but the tests where successful. so i don't think it is a problem.
I think its needed to run daily.sh before build-base case build-base would else setup the db schema from master.

**Comment by RalfHerzog** [comment]
Sounds good. Thanks!
