### ISSUE TITLE
request for distributed setups

### ISSUE THREAD

**Issue by cchance27** [setiseta/docker-librenms#17]
Any chance you could add a way to disable the various crontab'd services. Like if i want to use your image but only want it to run polling i could disable the discovery...

This is so that for distributed setups i can have 1 docker container run discovery and then say 3-4 that don't run the discovery but run only say the poller... being able to disable/enable the scheduled services via an environment variable would really be nice addition as right now i can't figure a way to do it.

While i'm at it, adding an environmental override for the rrdcached setting so that in a distributed deployment we can tell the librenms to use a specific rrdcached ip/dns for rrd would really be nice as i think right now your overriding it in the config when the container is recreated and it always sets it to the local unix socket instance.

**Comment by RalfHerzog** [comment]
So far there is no support for distributed polling. As a roadmap for integration, one should consider the described procedure from [here](https://github.com/librenms/librenms/blob/master/doc/Extensions/Distributed-Poller.md).
The distributed RRD path can be extracted (relatively easy) and can maybe be shared as a separate docker volume. I think we need another container setup routine to skip some of the configurations made on the main server. For example, migrating the database is not meaningful from a poller node

**Comment by cchance27** [comment]
I imagine it would look something like the below? :S

DISTRIBUTED=true/false    (triggers the usage of the below)
DISTRIBUTED_GROUP=xxxx
MIGRATEDB=true/false (true default)
POLLER =true/false (true default)
DISCOVERY=true/false (true default)
WEBUI=true/false (true default)
RRDCACHED_HOST=hostname:port (default to unix:/whateverTheDefaultIs)
MEMCACHED_HOST=hostname/ip
MEMCACHED_PORT=xxxx (11211 default)
MEMCACHED_TTL=xxxx (240 default)

that would then populate 
$config['memcached']['enable']  = true;
$config['memcached']['host']   
$config['memcached']['port']   
$config['memcached']['ttl']
$config['distributed_poller']    = true;                        
$config['distributed_poller_name']                       = file_get_contents('/proc/sys/kernel/hostname');
$config['distributed_poller_group']                      
$config['distributed_poller_memcached_host']            
$config['distributed_poller_memcached_port']       
$config['rrdcached']

**Comment by setiseta** [comment]
I don't know if its the right way.
Maybe it would be easier to generate dedicated images for this setup.
Whats your opinion @RalfHerzog ?

**Comment by RalfHerzog** [comment]
You are right. Another image could only offer variables which are not required to enable polling by default. However, I would like to see a docker-compose.yml with (a minimum of) two services (server and poller) as well as a shared volume (the rrd path) between them. The database and memcached can be linked.
@setiseta Do you have any experience running a poller node? I am especially interested in a config for that. Is it like that easy as mentioned above?
Can you please create another git branch for that feature? Branch: "poller" maybe?

**Comment by RalfHerzog** [comment]
Even better would be a separate project

**Comment by cchance27** [comment]
Their is no difference, as long as they share the same memcached/rrdcached and have the distributed memcached/settings set they will operate as a distrubuted system... (memcached handles the poller work jobs)

The only difference between a poller node or a discovery node or a web+discovery node is resources... 

Running a bunch of webui's is using up memory for no reason, or running discovery on multiple nodes is a waste of snmp polling... hence my recommendation to just add a way to set a node to not discovery or not run webui. 

Now i'm not saying the idea to break the project into multiple smaller projects isn't technically the "docker" way to do it as the "docker" way of doing things is 1 workjob per container, so technically poller.php discovery.php and the others should be crontab'd in different containers vs 1 container running bunch of services.

So guess the idea is which would be easier/better, ability to toggle what the image does (poll/disc/web) or have seperate images....

The only reason i recommended ENV based toggles is that the app files are 100% the same, all the containers would need the same PHP files and components so they would literally be identical images, except one would a cron for poller.php one would be a cron for discovery.php etc...

**Comment by cchance27** [comment]
As a note i'd imagine in something like kubernetes all the nodes would even share the same configmap, as all the configuration settings would be the same, just they would be running different service php's

**Comment by setiseta** [comment]
Thanks for your explanation.
I will look into this how it can easily be switched on and off.
Now we are using the default cron files from librenms repo.
With the split into discovery and poller nodes we need to make own cron files, and so need to check the updates if there is a change.

Any ideas how to make it maintainable / automated?
Extract the lines from the default?
Keep the 6 hours discovery and the 'new' discovery toghether?
Prepare the setup for use of the poller nodes on different hosts?

**Comment by cchance27** [comment]
i don't know enough about the cron routine but i'd imagine it would mean modifying the init.sh to include an if statement to check if $discovery = false  and instead of 
sed -i "s/discovery-wrapper.py 1/discovery-wrapper.py $POLLER/g" /etc/cron.d/librenms
you'd run
sed -i "s/discovery-wrapper.py 1//g" /etc/cron.d/librenms

and i imagine 
echo "/opt/librenms/discovery.php -u && /opt/librenms/discovery.php -h all && /opt/librenms/poller.php -h all" | at -M now + 1 minute

would need to be smarter... also something i just noticed, are you polling at 1 minute intervals? standard librenms polling is 5 minutes isn't it?

**Comment by setiseta** [comment]
where you see the 1 minute polling? its the default cron file from librenms used at the moment.

**Comment by cchance27** [comment]
last line of the init.sh

**Comment by setiseta** [comment]
this is only the first discovery & poller after startup.

**Comment by cchance27** [comment]
ah ok then it would just be the sed above that would allow to disable the
discovery on nodes that wouldn't be discovery nodes, that would leave only
the poller running, which i can't think of a reason we wouldn't want the
poller to always run on every node, unless we wanted a web only node i
suppose... but either way a toggle could be added so that if you set poller
or discovery = false that it just sed removes the discovery/poller from the
cron.

**Comment by setiseta** [comment]
@cchance27 have you tested it after the Pull request? Is it working for you?

**Comment by cchance27** [comment]
seems to be working great sorry for not getting back to you right away, ran into a diff issue recently but will open diff ticket think this can close
