### ISSUE TITLE
fping6 error?

### ISSUE THREAD

**Issue by cchance27** [setiseta/docker-librenms#18]
not sure whats causing this but the validate.php is throwing an error 

Fail: fping6 could not be executed. fping6 must have CAP_NET_RAW capability (getcap) or suid. Selinux exlusions may be required. (::1: error while sending ping: Cannot assign requested address ::1: error while sending ping: Cannot assign requested address ::1: error while sending ping: Cannot assign requested address ::1: error while sending ping: Cannot assign requested address ::1 is unreachable)
Fail: fping6 should have CAP_NET_RAW!
setcap cap_net_raw+ep /usr/bin/fping6

i tried adding capnetraw to the docker run but that isn't the issue apparently.

**Comment by setiseta** [comment]
Some special setup or just the default?

**Comment by setiseta** [comment]
```
docker-compose exec librenms bash
root@239324d96b9f:/# fping6 google.com
google.com is alive
root@239324d96b9f:/#
```
It's working on my maschine.
You have your docker setup for ipv6 right?
you got an ipv6 address for your container?

**Comment by cchance27** [comment]
hmmmm now that i think of it we don't use ipv6, is their a way to disable that in the container/config.php? to avoid the validate.php error

**Comment by setiseta** [comment]
I've requested on librenms repository. Waiting for input now.
As far as i can see, there is no option to disable it at the moment.

**Comment by setiseta** [comment]
If done a pull request on librenms:
https://github.com/librenms/librenms/pull/7757
This should change the error to only warn.
Waiting on merge.

**Comment by babbahotep** [comment]
followed setup guide and get the fping6 error as well.
root@4f26cb5edb92:/opt/librenms# getcap /usr/bin/fping6
/usr/bin/fping6 = cap_net_raw+ep
root@4f26cb5edb92:/opt/librenms# fping6 google.com
google.com: error while sending ping: Network is unreachable

any suggestions ?

**Comment by setiseta** [comment]
Yeah, this is not merged. Just waiting for it. Ignore it

**Comment by setiseta** [comment]
It got merged. It should now just warn if ipv6 is not enabled on the docker.
You may need to run dail.sh to get latest sources, or wait till tomorrow, or recreate the docker environment.
