### ISSUE TITLE
librenms php_network_getaddresses: getaddrinfo failed: Name or service not known

### ISSUE THREAD

**Issue by babbahotep** [setiseta/docker-librenms#19]
Hi,

installed mysql and librenms docker containers as per guide. 
Dumb question: do i need to run `docker-compose up -d` to start before 2 x docker run? I figured I just run `docker run mysql` and `docker run librenms` directly. 

When opening URL I get:
`php_network_getaddresses: getaddrinfo failed: Name or service not known`

validate.php gives me

`root@4f26cb5edb92:/opt/librenms# ./validate.php
====================================
Component | Version
--------- | -------
LibreNMS  | 1.33-128-g59625dc
DB Schema | 215
PHP       | 7.0.22-0ubuntu0.16.04.1
MySQL     | 10.2.10-MariaDB-10.2.10+maria~jessie
RRDTool   | 1.5.5
SNMP      | NET-SNMP 5.7.3
====================================

[OK]    Database connection successful
[OK]    Database schema correct
PHP Warning:  date(): Invalid date.timezone value 'Americas/Los_Angeles', we selected the timezone 'UTC' for now. in Command line code on line 1
[FAIL]  You have a different system timezone (Americas) than the php configured timezone (UTC)
	[FIX] Please correct either your system timezone or your timezone set in php.ini.
[WARN]  You have not added any devices yet.
	[FIX] You can add a device in the webui or with ./addhost.php
sh: 1: 1: not found
[FAIL]  fping6 could not be executed. fping6 must have CAP_NET_RAW capability (getcap) or suid. Selinux exlusions may be required.
 (::1: error while sending ping: Network is unreachable ::1: error while sending ping: Network is unreachable ::1: error while sending ping: Network is unreachable ::1: error while sending ping: Network is unreachable ::1 is unreachable)
[FAIL]  fping6 should have CAP_NET_RAW!
	[FIX] setcap cap_net_raw+ep /usr/bin/fping6
[WARN]  Your local git contains modified files, this could prevent automatic updates.
	[FIX] You can fix this with ./scripts/github-remove
	Modified Files:
	 html/plugins/Test/Test.inc.php
	 html/plugins/Test/Test.php`

daily.sh gives me:
`root@4f26cb5edb92:/opt/librenms# ./daily.sh
Re-running /opt/librenms/daily.sh as librenms user
Checking PHP version                               FAIL
MySQL Error: php_network_getaddresses: getaddrinfo failed: Name or service not known
MySQL Error: php_network_getaddresses: getaddrinfo failed: Name or service not known
grep: config.php: Permission denied
Updating SQL-Schema                                FAIL
MySQL Error: php_network_getaddresses: getaddrinfo failed: Name or service not known
Updating submodules                                OK
Cleaning up DB                                     FAIL
MySQL Error: php_network_getaddresses: getaddrinfo failed: Name or service not known
MySQL Error: php_network_getaddresses: getaddrinfo failed: Name or service not known
MySQL Error: php_network_getaddresses: getaddrinfo failed: Name or service not known
MySQL Error: php_network_getaddresses: getaddrinfo failed: Name or service not known
MySQL Error: php_network_getaddresses: getaddrinfo failed: Name or service not known
MySQL Error: php_network_getaddresses: getaddrinfo failed: Name or service not known
MySQL Error: php_network_getaddresses: getaddrinfo failed: Name or service not known
MySQL Error: php_network_getaddresses: getaddrinfo failed: Name or service not known
MySQL Error: php_network_getaddresses: getaddrinfo failed: Name or service not known
MySQL Error: php_network_getaddresses: getaddrinfo failed: Name or service not known
MySQL Error: php_network_getaddresses: getaddrinfo failed: Name or service not known
MySQL Error: php_network_getaddresses: getaddrinfo failed: Name or service not known
Fetching notifications                             FAIL
MySQL Error: php_network_getaddresses: getaddrinfo failed: Name or service not known
Caching PeeringDB data                             OK`

What am i missing ?

**Comment by setiseta** [comment]
With docker-compose up -d you start all from the file and daemonize it.
You can start without -d to attach and get the output. 
Or you can at any time attach to the logs with docker-compse logs -f where -f is to follow.

Can you paste your docker-compse.yml? 
And the output on startup?

**Comment by babbahotep** [comment]
Im on synology so this is what I get. I assumed I could just go ahead and run the docker run command in the readme.md.

`admin@Diskbox5:~/docker$ docker-compose up -d
ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.`

**Comment by setiseta** [comment]
I'm sorry, i don't know the synology with docker.
on normal linux hosts with ```docker run ... ``` you run an image directly, without any configuration from docker-compose.
is this 'admin' the root user there, or may there be a permission problem?

what tells ```docker info``` and ```docker-compose version```
Is there a socket /var/run/docker.sock or anywhere a docker.sock?

**Comment by setiseta** [comment]
closed cause of inactivity, you can reopen if its gets actual for you.
