### ISSUE TITLE
Snmp-scan cron?

### ISSUE THREAD

**Issue by cchance27** [setiseta/docker-librenms#20]
2 things really would it be possible for you to add in python-ipaddress to the build, so that snmp-scan.php will work inside the container.

Secondly any chance of adding a toggle to enable a weekly call to snmp-scan.php ? just wondering

**Comment by setiseta** [comment]
Both is possible.

I'm a bit busy at the moment.
Maybe its faster if you can post a pull request, if this is possible for you.

**Comment by setiseta** [comment]
the configs can be set just in the config file. i think there is no need for a env variable. (else you would need some logic for array translation to the php config, wouldn't you?)
with ```python3 snmp-scan.py``` it seems to work, so there is no need for the module.
