### ISSUE TITLE
Example docker run command creates 50-server.cnf as a directory instead of file

### ISSUE THREAD

**Issue by jstevensen** [setiseta/docker-librenms#22]
Thank you for producing a docker container for librenms! I was testing this out last night and I've found that the use of relative paths in the docker run command end up creating a directory instead of a file.

Running this command: 
docker run -d -m 1g \
	-v `pwd`/mysql:/var/lib/mysql \
	-v `pwd`/50-server.cnf:/etc/mysql/mariadb.conf.d/50-server.cnf:ro \
	-e MYSQL_ROOT_PASSWORD=pwd4librenms \
	--name librenms-db \
	mariadb:latest

Creates 50-server.cnf as directory, instead of a folder.

Modifying the command to specify the full path results in 50-server.cnf being created as a file, as I believe is intended.

I found useful information in this post:
https://github.com/moby/moby/issues/24408

**Comment by setiseta** [comment]
Thank you for the information.
I've corrected the Readme with  commit 221b5d2
It would be nice if you can retest, and give some feedback.

**Comment by jstevensen** [comment]
Hi,

Tested this change. Unfortunately, the directory 50-server.cnf is still created. 

From https://docs.docker.com/engine/admin/volumes/bind-mounts/

> If you use -v or --volume to bind-mount a file or directory that does not yet exist on the Docker host, -v will create the endpoint for you. It is always created as a directory.

I'm not sure if there is a way around this when 50-server.cnf does not exist.

**Comment by RalfHerzog** [comment]
The only solution would be an extra database image I think. There is nothing against it but one more dependency to maintain

**Comment by setiseta** [comment]
you need to take the 50-server.cnf from repo, and place it on the mounted path.
then it won't generate a directory.
