### ISSUE TITLE
Issue with new git versions due to missing dependencies

### ISSUE THREAD

**Issue by cchance27** [setiseta/docker-librenms#24]
Looks like they started requiring composer to be installed so you need to call

./scripts/composer_wrapper.php install --no-dev 

during the first run, in addition you will need zip/unzip available

**Comment by cchance27** [comment]
2/9/2018 2:45:45 PMPHP Warning:  require(/opt/librenms/vendor/autoload.php): failed to open stream: No such file or directory in /opt/librenms/includes/init.php on line 44
2/9/2018 2:45:45 PMPHP Fatal error:  require(): Failed opening required '/opt/librenms/vendor/autoload.php' (include_path='.:/usr/share/php') in /opt/librenms/includes/init.php on line 44
2/9/2018 2:45:45 PMError: Missing dependencies, run: ./scripts/composer_wrapper.php install --no-dev
2/9/2018 2:45:45 PM
2/9/2018 2:45:45 PMPHP Warning:  require(/opt/librenms/vendor/autoload.php): failed to open stream: No such file or directory in /opt/librenms/includes/init.php on line 44
2/9/2018 2:45:45 PMPHP Fatal error:  require(): Failed opening required '/opt/librenms/vendor/autoload.php' (include_path='.:/usr/share/php') in /opt/librenms/includes/init.php on line 44
2/9/2018 2:45:45 PMwarning: unable to access '/root/.gitconfig': Permission denied
2/9/2018 2:45:45 PMwarning: unable to access '/root/.config/git/config': Permission denied
2/9/2018 2:45:47 PMCould not open input file: /opt/librenms/composer.phar
2/9/2018 2:45:47 PMwarning: unable to access '/root/.config/git/attributes': Permission denied
2/9/2018 2:45:48 PMwarning: unable to access '/root/.config/git/attributes': Permission denied

**Comment by setiseta** [comment]
thank you for the issue.
haven't seen this till now.
fixed with commit 51deba1

a feedback would be nice if its working for you.
