### ISSUE TITLE
Please include oxidized in this docker

### ISSUE THREAD

**Issue by Noname2244** [setiseta/docker-librenms#25]
Would it be possible to include oxidized in this docker?

**Comment by setiseta** [comment]
Is it needed to activate integration?

**Comment by Noname2244** [comment]
I couldn't answer if it's required but it would be easier and it is a really good combo.

**Comment by setiseta** [comment]
it should be used in different docker, and just connected togheter.

**Comment by setiseta** [comment]
so, i've tested this.
it works without any addition to the librenms docker.
i've setup the oxidized container oxidized/oxidized:latest
dockerhub link:
https://hub.docker.com/r/oxidized/oxidized/

setup the config, and router.rb and connected it now with librenms.
works fine, it shows the config tab on my cisco devices now.
