### ISSUE TITLE
Fresh image pull results in Error: Missing dependencies! Run the following command to fix:

### ISSUE THREAD

**Issue by natm** [setiseta/docker-librenms#28]
Since the Laravel PR was merged in LibreNMS upstream yesterday, my production and test seti/librenms container web interfaces both stopped. All endpoints presented:

```
Error: Missing dependencies! Run the following command to fix:
./scripts/composer_wrapper.php install --no-dev
```

I removed the containers, pulled the image again and ran the container, but same error.

Attempting to run ./daily.sh manually in the container or call the composer wrapper does not work either.

**Comment by Tocknicsu** [comment]
I try to enter into the container, and run ```./scripts/composer_wrapper.php install --no-dev```.
It report following:
```
  Problem 1
    - Installation request for erusev/parsedown 1.7.1 -> satisfiable by erusev/parsedown[1.7.1].
    - erusev/parsedown 1.7.1 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
  Problem 2
    - Installation request for laravel/framework v5.4.36 -> satisfiable by laravel/framework[v5.4.36].
    - laravel/framework v5.4.36 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
  Problem 3
    - laravel/framework v5.4.36 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - oriceon/toastr-5-laravel dev-master requires illuminate/session >=5.0.0 -> satisfiable by laravel/framework[v5.4.36].
    - Installation request for oriceon/toastr-5-laravel dev-master -> satisfiable by oriceon/toastr-5-laravel[dev-master].
```
It seems like some ext-mbstring error, and I try to run ```apt-get install php-mbstring``` and then ```./scripts/composer_wrapper.php install --no-dev```.

After I executed those commands, another error occured. It looks like some directories don't have correct permission.
```
mkdir -p /opt/librenms/bootstrap/cache /opt/librenms/storage /opt/librenms/logs
chown -R librenms:librenms /opt/librenms/bootstrap/cache /opt/librenms/storage /opt/librenms/logs
setfacl -R -m g::rwx /opt/librenms/bootstrap/cache /opt/librenms/storage /opt/librenms/logs
setfacl -d -m g::rwx /opt/librenms/bootstrap/cache /opt/librenms/storage /opt/librenms/logs
```

and after I run ```apt-get install acl``` and all above commands. Librenms works again.

**Comment by setiseta** [comment]
I will look into it. I think it will need some changes.

**Comment by setiseta** [comment]
the new packages are added.
you need to pull the newest version.
thank you for reporting.

**Comment by jsuelwald** [comment]
Good morning :)

I wantred to report that as well, but apparently i was too slow :) Thanks for fixing it and thanks a lot for supplying this docker image :)
