### ISSUE TITLE
Missing php7.0-mbstring

### ISSUE THREAD

**Issue by akileos** [setiseta/docker-librenms#29]
Hello,

 Composer is unhappy about mbstring missing on latest version, adding apt package php7.0-mbstring does the trick 

<pre>
# ./scripts/composer_wrapper.php install --no-dev
Do not run Composer as root/super user! See https://getcomposer.org/root for details
> LibreNMS\ComposerHelper::preInstall
Loading composer repositories with package information
Installing dependencies from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for erusev/parsedown 1.7.1 -> satisfiable by erusev/parsedown[1.7.1].
    - erusev/parsedown 1.7.1 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
  Problem 2
    - Installation request for laravel/framework v5.4.36 -> satisfiable by laravel/framework[v5.4.36].
    - laravel/framework v5.4.36 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
  Problem 3
    - laravel/framework v5.4.36 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - oriceon/toastr-5-laravel dev-master requires illuminate/session >=5.0.0 -> satisfiable by laravel/framework[v5.4.36].
    - Installation request for oriceon/toastr-5-laravel dev-master -> satisfiable by oriceon/toastr-5-laravel[dev-master].
</pre>

Edit : No sure if my issue is really legit, docker hub image seems to be working fine.

**Comment by setiseta** [comment]
it seems you are not on latest version.
you need to pull the image again.
latest version has changed to php 7.2

**Comment by setiseta** [comment]
please report back if its ok and close the issue.
or even if you still get some errors.

**Comment by akileos** [comment]
That's a quick reply ! I was building my local image from github, something might have gone wrong during build for some reason. Sorry for the noise.
As mentioned in edit HUB image seems to be fine, Ok to close.
