### ISSUE TITLE
Login wont work 

### ISSUE THREAD

**Issue by spqr2001** [setiseta/docker-librenms#32]
good morning , after rolling out initial login doesnt work , any idea how to fix ist ? 
Greets 
Michael

**Comment by setiseta** [comment]
Which compose file do you use?
And are there any changes to the default?

I've startet an empty environment and the default login works.

**Comment by spqr2001** [comment]
Hi , 


i used the default docker-compose.yml: 


version: '3'

services:
  mysql:
    image: mariadb 
    container_name: librenms-db
    volumes:
      - ./mysql:/var/lib/mysql
      - ./50-server.cnf:/etc/mysql/mariadb.conf.d/50-server.cnf:ro
    environment:
      - MYSQL_ROOT_PASSWORD=xxxxxxxx
      - MYSQL_DATABASE=librenms
      - TZ=Europe/Berlin
      - MYSQL_USER=librenms
      - MYSQL_PASSWORD=xxxxxxxx

    restart: always

  librenms:
    build: .
    image: seti/librenms
    container_name: librenms
    hostname: librenms
    volumes:
      - ./data:/data
    ports:
      - 8780:80
      - 514:514/tcp
      - 514:514/udp
    depends_on:
      - mysql
    environment:
      - DB_TYPE=mysql
      - DB_HOST=mysql
      - DB_NAME=librenms
      - DB_USER=librenms
      - DB_PASS=xxxxxxxx
      - TZ=Europe/Berlin
      - POLLER=24
      - SERVICES_ENABLED=1
      - UPDATE_CHANNEL=master
      - SYSLOG_ENABLED=1
    restart: always

**Comment by spqr2001** [comment]
Ich sehe wir können deutsch schreiben, das vereinfacht die Angelegenheit :-) Nachdem die Container deployed sind  und ich über per ngnix reverse proxy per ssl auf den Container connecte zeigt er mir zwar die Loginseite, aber librenms / librenms funzt nicht. Er akzeptiert die Zugangsdaten , reloaded aber nur die Loginseite. Ich könnte mir noch vorstellen das der nginx hiermit zu tun hat. Aktuell rolle ich die BASE URL als Https aus  - obwohl im Container ja nur plain http configuriert ist.

**Comment by spqr2001** [comment]
https://nsa.holudeck.com/

**Comment by setiseta** [comment]
Welcher Reverse Proxy wird verwendet?
Ich habe zusätzliche environments auf dem librenms container für den Reverse proxy:
```
      - VIRTUAL_HOST=test-librenms.domain.com
      - LETSENCRYPT_HOST=test-librenms.domain.com
```
Ich verwendet den jwilder/nginx-proxy mit dem jrcs/letsencrypt-nginx-proxy-companion.
Dabei ist es egal, dass im librenmscontainer nur http geliefert wird.

**Comment by setiseta** [comment]
Was mir aufgefallen ist, wo deine URL kurz verfügbar war, dass der Loginscreen aussieht als ob nicht alle Stylesheets etc. vorhanden sind.
Zum vergleich hier meine Temporäre URL:
https://tmp1234.coders.technology

**Comment by spqr2001** [comment]
Das sieht schon bedeutend besser aus .. . da stimmt was mit den Stylesheets nicht. Denke ich probiere auch jwilder / jrcs variante.

**Comment by setiseta** [comment]
Der jwilder ist einfach automatisiert.
Jedoch wenn es noch nicht fixiert ist würde ich auch einen blick auf Traefik empfehlen:
https://hub.docker.com/_/traefik/

Für kleine Umgebungen vielleicht zu komplex, aber man hat mehr möglichkeiten.
Der jwilder ist super einfach für kleine Umgebungen, jedoch wenn man bestimmte Einstellungen benötigt könnte er dort nicht ausreichen.
