### ISSUE TITLE
I can't access website after execute docker-compose 

### ISSUE THREAD

**Issue by goodguystw** [setiseta/docker-librenms#33]
Hi, 
I clone your git repo, and execute [ docker-compose up -d ] on my macbook, but can't access librenms website, the Chrome browser shows [ ERR_CONNECTION_REFUSED ], could you help me what's wrong with this ?

**Comment by goodguystw** [comment]
I found those service like nginx and php7.2-fpm are stopped in ubuntu container (librenms server), any idea ?

**Comment by setiseta** [comment]
Can you give some more Details?
Can you Post your compose file, or is it the default? 
And the docker-compose logs please

**Comment by goodguystw** [comment]
[ docker-compose.yml ] 

version: '3'

services:
  mysql:
    image: mariadb
    container_name: librenms-db
    volumes:
      - ./mysql:/var/lib/mysql
      - ./50-server.cnf:/etc/mysql/mariadb.conf.d/50-server.cnf:ro
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=librenms
      - TZ=Asia/Taipei
    restart: always

  librenms:
    build: .
    image: seti/librenms
    container_name: librenms
    hostname: librenms
    volumes:
      - ./data:/data
    ports:
      - 8081:80
      - 514:514/tcp
      - 514:514/udp
    depends_on:
      - mysql
    environment:
      - DB_TYPE=mysql
      - DB_HOST=mysql
      - DB_NAME=librenms
      - DB_USER=root
      - DB_PASS=password
      - TZ=Asia/Taipei
      - POLLER=24
      - SERVICES_ENABLED=1
      - UPDATE_CHANNEL=master
      - SYSLOG_ENABLED=1
    restart: always

**Comment by goodguystw** [comment]
*** Running /etc/my_init.d/10_syslog-ng.init...
[2019-09-19T12:20:10.159374] WARNING: Configuration file format is too old, syslog-ng is running in compatibility mode. Please update it to use the syslog-ng 3.13 format at your time of convenience. To upgrade the configuration, please review the warnings about incompatible changes printed by syslog-ng, and once completed change the @version header at the top of the configuration file.;
*** Running /etc/my_init.d/init.sh...
Current default time zone: 'Asia/Taipei'
Local time is now:      Thu Sep 19 12:20:11 CST 2019.
Universal Time is now:  Thu Sep 19 04:20:11 UTC 2019.
Clone Repo from github.
Created directory: /var/lib/snmp/mib_indexes
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Installing librenms/librenms (dev-master a0c2df6cd957906f436b480574389e68c7c041c3)

**Comment by goodguystw** [comment]
oh my god, it runs smoothly now, I don't know why... but still thanks!

**Comment by setiseta** [comment]
maybe cause it needs some time on initial run.
