### ISSUE TITLE
I have trouble when apt-get install php 7.4

### ISSUE THREAD

**Issue by CHR211529** [setiseta/docker-librenms#35]
Error: retrieving gpg key timed out.
what should i do, anyone can help me? thank u

**Comment by setiseta** [comment]
Php 7.4 is installed in the Image, what are you trying?

**Comment by DCW-CHR** [comment]
yes, when I run this command：docker-compose up -d，
it run step 4，appear this error:
`Step 4/18 : RUN echo 'APT::Install-Recommends 0;' >> /etc/apt/apt.conf.d/01norecommends && 	echo 'APT::Install-Suggests 0;' >> /etc/apt/apt.conf.d/01norecommends &&         add-apt-repository ppa:ondrej/php -y && 	apt-get update -q && 	apt-get upgrade -y -o Dpkg::Options::="--force-confold" && 	apt-get install -y 		acl composer php7.4-mbstring php7.4-cli php7.4-mysql php7.4-gd php7.4-snmp php-pear php7.4-curl php-memcached 		php7.4-fpm snmp graphviz php7.4-json php7.4-opcache nginx-full fping 		imagemagick whois mtr-tiny nmap python-mysqldb snmpd php7.4-ldap syslog-ng 		php-net-ipv6 php-imagick rrdtool rrdcached git at mysql-client nagios-plugins sudo ipmitool         memcached php7.4-xml php7.4-zip python-memcache make && 	apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
 ---> Running in 802e28d4eaf9
Error: retrieving gpg key timed out.`
so i think that  it is going install php 7.4 and something error happen. I  cat  Dockfile and I went to install it manually like this.
`apt-get install software-properties-common`
`add-apt-repository ppa:ondrej/php`
`apt-get update`
`apt-get install php7.4 php7.4-fpm php7.4-mysql php7.4-gd php7.4-mbstring`
it seems like works, but print all the time now, Is it normal？It's been more than half an hour，thank u very much!
`Get:15 http://archive.ubuntu.com/ubuntu bionic/universe Sources [11.5 MB]
Get:15 http://archive.ubuntu.com/ubuntu bionic/universe Sources [11.5 MB]
Get:15 http://archive.ubuntu.com/ubuntu bionic/universe Sources [11.5 MB]
Get:15 http://archive.ubuntu.com/ubuntu bionic/universe Sources [11.5 MB]
Get:15 http://archive.ubuntu.com/ubuntu bionic/universe Sources [11.5 MB]
Get:15 http://archive.ubuntu.com/ubuntu bionic/universe Sources [11.5 MB]
Get:15 http://archive.ubuntu.com/ubuntu bionic/universe Sources [11.5 MB]
Get:15 http://archive.ubuntu.com/ubuntu bionic/universe Sources [11.5 MB]
Get:15 http://archive.ubuntu.com/ubuntu bionic/universe Sources [11.5 MB]
Get:15 http://archive.ubuntu.com/ubuntu bionic/universe Sources [11.5 MB]
Get:15 http://archive.ubuntu.com/ubuntu bionic/universe Sources [11.5 MB]
Get:15 http://archive.ubuntu.com/ubuntu bionic/universe Sources [11.5 MB]`

**Comment by setiseta** [comment]
If you do docker-compose up -d it should pull the Image not run anything from the Dockerfile, or do you have added build options in your compose?
Can you Post the compose file?
