### ISSUE TITLE
Python requirements not met

### ISSUE THREAD

**Issue by jyhsu2000** [setiseta/docker-librenms#38]
After I clone the repo and use `docker-compose up -d` to startup the service,
this error shown in Notifications page

> ## Error: Python requirements not met
> Python 3 dependencies are missing. You need to install them via pip3 install -r requirements.txt or system packages to continue to receive updates. If you do not install Python 3 and required packages, LibreNMS will continue to function but stop receiving bug fixes and updates.
2020-10-17 00:00:00 | Source: daily.sh

![image](https://user-images.githubusercontent.com/6276648/96338787-009eb400-10c3-11eb-8933-b78a3aea9152.png)

I know I can use `docker exec` to run `pip3 install -r requirements.txt` every time to fix it temporary.
But I think this issue should be fixed fundamentally.

**Comment by setiseta** [comment]
Commit f6630af should fix it

**Comment by jyhsu2000** [comment]
Thanks.
It has been fixed.
