### ISSUE TITLE
Weird Link issue

### ISSUE THREAD

**Issue by sesgigikimo** [setiseta/docker-librenms#42]
Hi,

While clicking on any diagram, the address cannot link to correct address.

Please see the screen shot.
[https://imgur.com/a/DS4Im7Y](https://imgur.com/a/DS4Im7Y)

**Comment by setiseta** [comment]
Hi,

it seems there is somesing in the config not set, for the base_url.
Can you post your config, and docker-compose.yml?
(data/config/config.php)

Just to inform you, there is now an official docker for librenms:
https://hub.docker.com/r/librenms/librenms

**Comment by sesgigikimo** [comment]
Hi,

After i set the base_url, the problem solved. 
Thank you
