### ISSUE TITLE
config.php grows with every container start

### ISSUE THREAD

**Issue by RalfHerzog** [setiseta/docker-librenms#8]
I noticed that the `/data/config/config.php` inside the container grows with every start. This results because `init.sh` append lines to `config.php` even if they already exist.

Solutions I can imagine:
- Make config.php read-only persistent outside the container (not very handy)
- Use a templating approach where lines getting replaced instead to be overwritten (`sed -i` is maybe a choice; with a regex)
- Use a templating file (maybe `config.php.template`) specifying the structure of `config.php` and substitute values on container start

I am open for hints

**Comment by setiseta** [comment]
yes i have used sed -i
I see that I have not checked enough the Pull Requests.
The intention is to not overwrite user settings every restart. this is cause i used sed -i.
